version: "3.9"

services:
  karma-api:
    container_name: karma-api
    image: karma-api
    build:
      context: ../Api
      dockerfile: Dockerfile
    ports:
      - "5051:80"
    depends_on:
      - karma-rmq

  karma-rmq:
    container_name: karma-rmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
