services:
  karma-api:
    container_name: karma-api
    image: karma-api
    build:
      context: ./Api
      dockerfile: Dockerfile
    ports:
      - "5051:80"
    depends_on:
      - karma-rmq
      - karma-db

  karma-db:
    container_name: karma-db
    image: mssql-graph-db
    build:
      context: ./Database
      dockerfile: Dockerfile
    ports:
      - 5431:1433
    environment:
      - SA_PASSWORD=Yukon900
      - ACCEPT_EULA=Y

  karma-rmq:
    container_name: karma-rmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    external: true
    name: karma-network